---
apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: zt04032301
  tags: []
  description: zt04032301
  annotations:
    github.com/project-slug: chriszacny/zt04032301

spec:
  type: service
  owner: group:cedi
  lifecycle: experimental
